version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: camagru-nginx
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - camagru-network

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: camagru-php
    volumes:
      - ./public:/var/www/html
    networks:
      - camagru-network

networks:
  camagru-network:
    driver: bridge
