services:
  nginx:
    image: nginx:1.26.2
    container_name: camagru-nginx
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - camagru-network

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: camagru-php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - camagru-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: camagru-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - camagru-network

  db:
    image: mysql:5.7
    container_name: camagru-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/sql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "3306:3306"
    networks:
      - camagru-network

volumes:
  db_data:

networks:
  camagru-network:
    driver: bridge
